# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
before_install:
  - chmod +x install-NeticaAPI.sh
  - chmod +x install-RNetica.sh
install:
  - which unzip
  - ./install-NeticaAPI.sh
  - ./install-RNetica.sh
  - Rscript -e 'install.packages(c("devtools", "knitr", "dplyr", "purrr", "readr", "rprojroot", "tidyr", "rmarkdown"))'
warnings_are_errors: false
